# questions.py
BIG_QUIZ_POOL = {
    "1-4 sinflar (Beginner)": [
        # Животные и Цвета (40 шт)
        {"q": "What color is an apple?", "a": "red"}, {"q": "Is a pig pink?", "a": "yes"},
        {"q": "Translate 'Kuchuk':", "a": "dog"}, {"q": "Translate 'Fil':", "a": "elephant"},
        {"q": "A crocodile is... (Green/Red)", "a": "green"}, {"q": "Does a cat bark? (Yes/No)", "a": "no"},
        {"q": "How many legs does a spider have?", "a": "8"}, {"q": "Translate 'Sariq':", "a": "yellow"},
        {"q": "A lion is a... (King/Queen)", "a": "king"}, {"q": "Is a mouse small?", "a": "yes"},
        {"q": "Translate 'Quyon':", "a": "rabbit"}, {"q": "What color is an orange?", "a": "orange"},
        {"q": "A bear is... (Big/Small)", "a": "big"}, {"q": "Translate 'Qizil':", "a": "red"},
        {"q": "Does a fish swim? (Yes/No)", "a": "yes"}, {"q": "Translate 'Oq':", "a": "white"},
        {"q": "A zebra has... (Stripes/Dots)", "a": "stripes"}, {"q": "Translate 'Qora':", "a": "black"},
        {"q": "Is a monkey funny?", "a": "yes"}, {"q": "Translate 'Tovuq':", "a": "chicken"},
        {"q": "A cow says... (Moo/Meow)", "a": "moo"}, {"q": "Translate 'Ot':", "a": "horse"},
        {"q": "Is a giraffe tall?", "a": "yes"}, {"q": "Translate 'Ari':", "a": "bee"},
        {"q": "What color is a lemon?", "a": "yellow"}, {"q": "Translate 'Sichqon':", "a": "mouse"},
        {"q": "A frog is... (Green/Pink)", "a": "green"}, {"q": "Translate 'Sher':", "a": "lion"},
        {"q": "Do birds fly? (Yes/No)", "a": "yes"}, {"q": "Translate 'Toshbaqa':", "a": "turtle"},
        {"q": "What color is the sky?", "a": "blue"}, {"q": "Translate 'Bo'ri':", "a": "wolf"},
        {"q": "Is a snake long?", "a": "yes"}, {"q": "Translate 'Tilkicha':", "a": "fox"},
        {"q": "A sheep says... (Baa/Woof)", "a": "baa"}, {"q": "Translate 'Kiyik':", "a": "deer"},
        {"q": "What color is grass?", "a": "green"}, {"q": "Translate 'Laylak':", "a": "stork"},
        {"q": "Is an ant big?", "a": "no"}, {"q": "Translate 'Hulqar':", "a": "whale"},
        # Школа и Числа (40 шт)
        {"q": "What is 5 + 5?", "a": "ten"}, {"q": "What is 2 + 1?", "a": "three"},
        {"q": "How many fingers do you have?", "a": "10"}, {"q": "Translate 'Maktab':", "a": "school"},
        {"q": "You write with a... (Pen/Car)", "a": "pen"}, {"q": "Translate 'Kitob':", "a": "book"},
        {"q": "A, B, C, ... What's next?", "a": "d"}, {"q": "Is a ruler long?", "a": "yes"},
        {"q": "Ten minus two is...", "a": "eight"}, {"q": "One, two, ..., four.", "a": "three"},
        {"q": "Translate 'O'qituvchi':", "a": "teacher"}, {"q": "Where do you study?", "a": "school"},
        {"q": "What is 7 + 0?", "a": "seven"}, {"q": "Translate 'Sinf':", "a": "class"},
        {"q": "You sit on a... (Chair/Table)", "a": "chair"}, {"q": "Is 100 a big number?", "a": "yes"},
        {"q": "Translate 'Doska':", "a": "board"}, {"q": "What color is a blackboard?", "a": "black"},
        {"q": "How many days in a week?", "a": "7"}, {"q": "Translate 'Qalam':", "a": "pencil"},
        {"q": "What is 6 + 4?", "a": "ten"}, {"q": "Translate 'Daftar':", "a": "notebook"},
        {"q": "Is your bag heavy?", "a": "yes"}, {"q": "Translate 'O'chirg'ich':", "a": "eraser"},
        {"q": "What is 1 + 1?", "a": "two"}, {"q": "Translate 'Sumka':", "a": "bag"},
        {"q": "Is the teacher kind?", "a": "yes"}, {"q": "Translate 'Talaba':", "a": "student"},
        {"q": "What is 20 - 10?", "a": "ten"}, {"q": "Translate 'Dars':", "a": "lesson"},
        {"q": "How many ears do you have?", "a": "2"}, {"q": "Translate 'Xona':", "a": "room"},
        {"q": "What is 3 + 3?", "a": "six"}, {"q": "Translate 'Qog'oz':", "a": "paper"},
        {"q": "Is a pencil short?", "a": "yes"}, {"q": "Translate 'Lug'at':", "a": "dictionary"},
        {"q": "What is 9 + 1?", "a": "ten"}, {"q": "Translate 'Imtihon':", "a": "exam"},
        {"q": "How many eyes do you have?", "a": "2"}, {"q": "Translate 'Ruchka':", "a": "pen"},
        # Семья и Дом (40 шт)
        {"q": "Translate 'Ona':", "a": "mother"}, {"q": "Translate 'Ota':", "a": "father"},
        {"q": "My father's sister is my...", "a": "aunt"}, {"q": "Translate 'Oila':", "a": "family"},
        {"q": "I sleep in my... (Bed/Kitchen)", "a": "bed"}, {"q": "Translate 'Uy':", "a": "house"},
        {"q": "Is your brother a boy or a girl?", "a": "boy"}, {"q": "Translate 'Aka':", "a": "brother"},
        {"q": "Translate 'Opa':", "a": "sister"}, {"q": "A baby is... (Young/Old)", "a": "young"},
        {"q": "Translate 'Buva':", "a": "grandfather"}, {"q": "Translate 'Buvijon':", "a": "grandmother"},
        {"q": "Where do you cook? (Kitchen/Park)", "a": "kitchen"}, {"q": "Translate 'Eshik':", "a": "door"},
        {"q": "Translate 'Deraza':", "a": "window"}, {"q": "Is a house big?", "a": "yes"},
        {"q": "My mom's son is my...", "a": "brother"}, {"q": "Translate 'Ism':", "a": "name"},
        {"q": "Translate 'Amaki':", "a": "uncle"}, {"q": "Translate 'Xola':", "a": "aunt"},
        {"q": "Where do you wash? (Bathroom/Garden)", "a": "bathroom"}, {"q": "Translate 'Devor':", "a": "wall"},
        {"q": "Translate 'Tom':", "a": "roof"}, {"q": "Is the floor clean?", "a": "yes"},
        {"q": "Translate 'O'g'il':", "a": "son"}, {"q": "Translate 'Qiz':", "a": "daughter"},
        {"q": "Where do you eat? (Dining room/Garage)", "a": "dining room"}, {"q": "Translate 'Kalit':", "a": "key"},
        {"q": "Translate 'Chiroq':", "a": "light"}, {"q": "Is the bed soft?", "a": "yes"},
        {"q": "Translate 'Qo'shni':", "a": "neighbor"}, {"q": "Translate 'Bolalar':", "a": "children"},
        {"q": "Where is the car? (Garage/Bedroom)", "a": "garage"}, {"q": "Translate 'Bog'':", "a": "garden"},
        {"q": "Translate 'Gul':", "a": "flower"}, {"q": "Is the garden green?", "a": "yes"},
        {"q": "Translate 'Krovat':", "a": "bed"}, {"q": "Translate 'Oshxona':", "a": "kitchen"},
        {"q": "Translate 'Yotoqxona':", "a": "bedroom"}, {"q": "Translate 'Mehmonxona':", "a": "living room"}
    ],

    "5-9 sinflar (Intermediate)": [
        # Грамматика (40 шт)
        {"q": "Past Simple of 'Go'?", "a": "went"}, {"q": "Past Simple of 'See'?", "a": "saw"},
        {"q": "I ___ (was/were) there.", "a": "was"}, {"q": "She ___ (works/work) here.", "a": "works"},
        {"q": "They ___ (are/is) students.", "a": "are"}, {"q": "Translate 'Kelajak':", "a": "future"},
        {"q": "He ___ (didn't/don't) know.", "a": "didn't"}, {"q": "Are you ___ (older/old) than me?", "a": "older"},
        {"q": "Past Simple of 'Eat'?", "a": "ate"}, {"q": "I ___ (have/has) a car.", "a": "have"},
        {"q": "She ___ (has/have) a dog.", "a": "has"}, {"q": "Translate 'Hozir':", "a": "now"},
        {"q": "We ___ (play/plays) football.", "a": "play"}, {"q": "Past Simple of 'Do'?", "a": "did"},
        {"q": "I am ___ (better/good) than him.", "a": "better"}, {"q": "Translate 'Kecha':", "a": "yesterday"},
        {"q": "Will you ___ (go) tomorrow?", "a": "go"}, {"q": "Translate 'Doim':", "a": "always"},
        {"q": "She is the ___ (most/more) beautiful.", "a": "most"}, {"q": "Past Simple of 'Buy'?", "a": "bought"},
        {"q": "Past Simple of 'Speak'?", "a": "spoke"}, {"q": "Translate 'Ba'zan':", "a": "sometimes"},
        {"q": "Have you ___ (ever/never) been to London?", "a": "ever"}, {"q": "Translate 'Tezda':", "a": "quickly"},
        {"q": "She ___ (don't/doesn't) like milk.", "a": "doesn't"}, {"q": "Translate 'Ertaga':", "a": "tomorrow"},
        {"q": "Past Simple of 'Run'?", "a": "ran"}, {"q": "Translate 'Oson':", "a": "easy"},
        {"q": "Is he ___ (strong) than you?", "a": "stronger"}, {"q": "Translate 'Qiyin':", "a": "difficult"},
        {"q": "We ___ (are/is) going to the cinema.", "a": "are"}, {"q": "Translate 'Hafta':", "a": "week"},
        {"q": "Past Simple of 'Sleep'?", "a": "slept"}, {"q": "Translate 'Yil':", "a": "year"},
        {"q": "I ___ (am/is) watching TV now.", "a": "am"}, {"q": "Translate 'Oy':", "a": "month"},
        {"q": "She ___ (can/cans) swim well.", "a": "can"}, {"q": "Translate 'Vaqt':", "a": "time"},
        {"q": "Past Simple of 'Take'?", "a": "took"}, {"q": "Translate 'Bugun':", "a": "today"},
        # Лексика и Мир (40 шт)
        {"q": "Capital of the UK?", "a": "london"}, {"q": "Translate 'Sayohat':", "a": "travel"},
        {"q": "A person who flies a plane?", "a": "pilot"}, {"q": "Where is Paris?", "a": "france"},
        {"q": "Translate 'Shifokor':", "a": "doctor"}, {"q": "Translate 'Poytaxt':", "a": "capital"},
        {"q": "Synonym of 'Large'?", "a": "big"}, {"q": "Translate 'Qishloq':", "a": "village"},
        {"q": "Which is colder: Winter or Summer?", "a": "winter"}, {"q": "Translate 'Ob-havo':", "a": "weather"},
        {"q": "A week has ___ days.", "a": "7"}, {"q": "Translate 'Dengiz':", "a": "sea"},
        {"q": "Where do you buy bread?", "a": "bakery"}, {"q": "Translate 'Non':", "a": "bread"},
        {"q": "Opposite of 'Fast'?", "a": "slow"}, {"q": "Translate 'Baqquvat':", "a": "strong"},
        {"q": "A doctor works in a... (Hospital/Park)", "a": "hospital"}, {"q": "Translate 'Dam olish':", "a": "rest"},
        {"q": "Translate 'Tog'':", "a": "mountain"}, {"q": "Is the ocean salt?", "a": "yes"},
        {"q": "Translate 'Daryo':", "a": "river"}, {"q": "Where is the Statue of Liberty?", "a": "usa"},
        {"q": "Translate 'Kasalxona':", "a": "hospital"}, {"q": "Translate 'Dorixona':", "a": "pharmacy"},
        {"q": "Opposite of 'Cheap'?", "a": "expensive"}, {"q": "Translate 'Boy':", "a": "rich"},
        {"q": "Translate 'Kambag'al':", "a": "poor"}, {"q": "Is London a big city?", "a": "yes"},
        {"q": "Translate 'Aeroport':", "a": "airport"}, {"q": "Translate 'Bekat':", "a": "station"},
        {"q": "Where do you see a movie? (Cinema/Gym)", "a": "cinema"}, {"q": "Translate 'Muzey':", "a": "museum"},
        {"q": "Translate 'Chipta':", "a": "ticket"}, {"q": "Is the sun a star?", "a": "yes"},
        {"q": "Translate 'Yulduz':", "a": "star"}, {"q": "Translate 'Oy':", "a": "moon"},
        {"q": "Where do you buy clothes? (Shop/Library)", "a": "shop"}, {"q": "Translate 'Bozo':", "a": "market"},
        {"q": "Translate 'Ko'cha':", "a": "street"}, {"q": "Translate 'Shahar':", "a": "city"},
        # Хобби и Спорт (40 шт)
        {"q": "Translate 'Futbol':", "a": "football"}, {"q": "Do you play ___ guitar? (the/a)", "a": "the"},
        {"q": "Translate 'Suzish':", "a": "swimming"}, {"q": "A person who sings is a...", "a": "singer"},
        {"q": "Translate 'Rasm chizish':", "a": "drawing"}, {"q": "I like ___ (listen) to music.", "a": "listening"},
        {"q": "Translate 'Kitob o'qish':", "a": "reading"}, {"q": "Is Messi a football player?", "a": "yes"},
        {"q": "Translate 'Musiqa':", "a": "music"}, {"q": "I am fond ___ sport. (of/in)", "a": "of"},
        {"q": "Translate 'G'alaba':", "a": "victory"}, {"q": "Opposite of 'Win'?", "a": "lose"},
        {"q": "Translate 'Jamoa':", "a": "team"}, {"q": "Translate 'Hordiq':", "a": "leisure"},
        {"q": "I play tennis ___ Sundays. (on/at)", "a": "on"}, {"q": "Translate 'Qiziqish':", "a": "interest"},
        {"q": "Is chess a sport?", "a": "yes"}, {"q": "Translate 'Shaxmat':", "a": "chess"},
        {"q": "Translate 'Yugurish':", "a": "running"}, {"q": "A person who dances is a...", "a": "dancer"},
        {"q": "Translate 'Raqs':", "a": "dance"}, {"q": "I enjoy ___ (swim).", "a": "swimming"},
        {"q": "Translate 'Velosiped':", "a": "bicycle"}, {"q": "Do you like movies?", "a": "yes"},
        {"q": "Translate 'Kino':", "a": "movie"}, {"q": "Translate 'Teatr':", "a": "theatre"},
        {"q": "A person who acts in movies?", "a": "actor"}, {"q": "Translate 'Aktyor':", "a": "actor"},
        {"q": "Translate 'Foydali':", "a": "useful"}, {"q": "Is sport good for health?", "a": "yes"},
        {"q": "Translate 'Sog'lom':", "a": "healthy"}, {"q": "Translate 'Mashq':", "a": "exercise"},
        {"q": "Where do you play football? (Stadium/Library)", "a": "stadium"}, {"q": "Translate 'To'p':", "a": "ball"},
        {"q": "Translate 'Darvoza':", "a": "goal"}, {"q": "Translate 'Hakam':", "a": "referee"},
        {"q": "Is basketball popular?", "a": "yes"}, {"q": "Translate 'Balandlik':", "a": "height"},
        {"q": "Translate 'Musobaqa':", "a": "competition"}, {"q": "Translate 'Sovrin':", "a": "prize"}
    ],

    "10-11 sinflar va Kattalar": [
        # Бизнес и Работа (40 шт)
        {"q": "What is 'CEO'?", "a": "chief executive officer"}, {"q": "Translate 'Muzokaralar':", "a": "negotiations"},
        {"q": "Translate 'Mas'uliyat':", "a": "responsibility"},
        {"q": "A person who starts a business?", "a": "entrepreneur"},
        {"q": "Translate 'Foyda':", "a": "profit"}, {"q": "Translate 'Taqdimot':", "a": "presentation"},
        {"q": "Translate 'Shartnoma':", "a": "contract"}, {"q": "What is 'HR'?", "a": "human resources"},
        {"q": "Translate 'Ishsizlik':", "a": "unemployment"}, {"q": "Translate 'Maosh':", "a": "salary"},
        {"q": "Opposite of 'Import'?", "a": "export"}, {"q": "Translate 'Sarmoya':", "a": "investment"},
        {"q": "What is 'PR'?", "a": "public relations"}, {"q": "Translate 'Mijoz':", "a": "client"},
        {"q": "Translate 'Bozor':", "a": "market"}, {"q": "Is 'Deadline' a final date?", "a": "yes"},
        {"q": "Translate 'Hamkorlik':", "a": "partnership"}, {"q": "What is 'IT'?", "a": "information technology"},
        {"q": "Translate 'Kompaniya':", "a": "company"}, {"q": "Translate 'Soliq':", "a": "tax"},
        {"q": "Translate 'Ishga olish':", "a": "hiring"}, {"q": "Translate 'Suhbat':", "a": "interview"},
        {"q": "What is 'CV'?", "a": "curriculum vitae"}, {"q": "Translate 'Tajriba':", "a": "experience"},
        {"q": "Translate 'Ko'nikma':", "a": "skill"}, {"q": "Opposite of 'Success'?", "a": "failure"},
        {"q": "Translate 'Boshqaruv':", "a": "management"}, {"q": "Translate 'Xodim':", "a": "employee"},
        {"q": "Translate 'Rahbar':", "a": "leader"}, {"q": "Is 'Efficiency' important?", "a": "yes"},
        {"q": "Translate 'Raqobat':", "a": "competition"}, {"q": "Translate 'Strategiya':", "a": "strategy"},
        {"q": "What is 'Marketing'?", "a": "marketing"}, {"q": "Translate 'Mahsulot':", "a": "product"},
        {"q": "Translate 'Xizmat':", "a": "service"}, {"q": "Translate 'Sifat':", "a": "quality"},
        {"q": "Translate 'Budjet':", "a": "budget"}, {"q": "Translate 'Xarajat':", "a": "expense"},
        {"q": "Translate 'Daromad':", "a": "income"}, {"q": "Is 'Networking' useful?", "a": "yes"},
        # Продвинутая Грамматика (40 шт)
        {"q": "If I ___ (be) you, I'd go.", "a": "were"}, {"q": "Synonym of 'Precise'?", "a": "accurate"},
        {"q": "I look forward to ___ (meet) you.", "a": "meeting"},
        {"q": "Passive: 'I made it' -> 'It ___ made'.", "a": "was"},
        {"q": "Translate 'Muvaffaqiyat':", "a": "success"}, {"q": "Hardly ___ (had I / I had) started.", "a": "had i"},
        {"q": "Translate 'Imkoniyat':", "a": "opportunity"},
        {"q": "By 5 PM, I ___ (finish) it.", "a": "will have finished"},
        {"q": "Translate 'Barqarorlik':", "a": "stability"}, {"q": "She suggested ___ (go) there.", "a": "going"},
        {"q": "Translate 'Rivojlanish':", "a": "development"},
        {"q": "I wish I ___ (know) it earlier.", "a": "had known"},
        {"q": "Translate 'Bilim':", "a": "knowledge"}, {"q": "Despite ___ (rain), we went out.", "a": "the rain"},
        {"q": "It's no use ___ (cry).", "a": "crying"}, {"q": "Translate 'Yutuq':", "a": "achievement"},
        {"q": "She is used to ___ (work) late.", "a": "working"},
        {"q": "Translate 'Mustaqillik':", "a": "independence"},
        {"q": "Had I known, I ___ (would have) come.", "a": "would have"},
        {"q": "Translate 'Zarur':", "a": "necessary"},
        {"q": "Translate 'Ehtimol':", "a": "probably"}, {"q": "I'd rather you ___ (not/go).", "a": "didn't go"},
        {"q": "Translate 'Tasdiqlash':", "a": "confirm"}, {"q": "She denied ___ (steal) the money.", "a": "stealing"},
        {"q": "Translate 'Rad etmoq':", "a": "refuse"}, {"q": "I am looking ___ my keys. (for/at)", "a": "for"},
        {"q": "Translate 'Chidamoq':", "a": "endure"}, {"q": "She avoided ___ (see) him.", "a": "seeing"},
        {"q": "Translate 'Foyda':", "a": "benefit"}, {"q": "It depends ___ you. (on/in)", "a": "on"},
        {"q": "Translate 'Ayblamoq':", "a": "accuse"}, {"q": "He apologized ___ being late. (for/to)", "a": "for"},
        {"q": "Translate 'E'tirof etmoq':", "a": "acknowledge"},
        {"q": "She is capable ___ doing it. (of/to)", "a": "of"},
        {"q": "Translate 'Aniq':", "a": "obvious"}, {"q": "He is interested ___ art. (in/on)", "a": "in"},
        {"q": "Translate 'Ajoyib':", "a": "wonderful"}, {"q": "Translate 'G'alati':", "a": "strange"},
        {"q": "Translate 'Muhim':", "a": "important"}, {"q": "Translate 'Xavfsiz':", "a": "safe"},
        # Идиомы и Культура (40 шт)
        {"q": "Idiom: 'Piece of ___' (Very easy)", "a": "cake"}, {"q": "Idiom: 'Break a ___' (Good luck)", "a": "leg"},
        {"q": "Synonym of 'Exhausted'?", "a": "tired"}, {"q": "Opposite of 'Artificial'?", "a": "natural"},
        {"q": "Translate 'Madaniyat':", "a": "culture"}, {"q": "Idiom: 'Under the ___' (Feeling sick)", "a": "weather"},
        {"q": "Translate 'Jamiyat':", "a": "society"}, {"q": "What is a 'Brain drain'?", "a": "migration of experts"},
        {"q": "Translate 'Atrof-muhit':", "a": "environment"}, {"q": "Idiom: 'Cost an arm and a ___'", "a": "leg"},
        {"q": "Translate 'Global isish':", "a": "global warming"}, {"q": "Synonym of 'Huge'?", "a": "enormous"},
        {"q": "Translate 'Texnologiya':", "a": "technology"}, {"q": "Idiom: 'Hit the ___' (Go to sleep)", "a": "hay"},
        {"q": "Translate 'Siyosat':", "a": "politics"}, {"q": "Opposite of 'Generous'?", "a": "mean"},
        {"q": "Translate 'Iqtisodiyot':", "a": "economy"}, {"q": "Synonym of 'Ancient'?", "a": "old"},
        {"q": "Translate 'Sog'liq':", "a": "health"}, {"q": "Idiom: 'Once in a ___ moon'", "a": "blue"},
        {"q": "Translate 'San'at':", "a": "art"}, {"q": "Idiom: 'Kill two birds with one ___'", "a": "stone"},
        {"q": "Translate 'Tarix':", "a": "history"}, {"q": "Idiom: 'Cry over spilt ___'", "a": "milk"},
        {"q": "Translate 'Kelajak':", "a": "future"}, {"q": "Idiom: 'The best of both ___'", "a": "worlds"},
        {"q": "Translate 'Adabiyot':", "a": "literature"}, {"q": "Idiom: 'See eye to ___'", "a": "eye"},
        {"q": "Translate 'Fan':", "a": "science"}, {"q": "Idiom: 'Call it a ___' (Finish work)", "a": "day"},
        {"q": "Translate 'Kashfiyot':", "a": "discovery"}, {"q": "Idiom: 'Beat around the ___'", "a": "bush"},
        {"q": "Translate 'Ixtiro':", "a": "invention"}, {"q": "Idiom: 'Bite off more than you can ___'", "a": "chew"},
        {"q": "Translate 'Ma'rifat':", "a": "enlightenment"}, {"q": "Idiom: 'Let the cat out of the ___'", "a": "bag"},
        {"q": "Translate 'Iste'dod':", "a": "talent"}, {"q": "Idiom: 'Burning the midnight ___'", "a": "oil"},
        {"q": "Translate 'Ziyoli':", "a": "intellectual"}, {"q": "Idiom: 'Steal someone's ___'", "a": "thunder"}
    ]
}
